### ISSUE TITLE
module not available in Module Deployment in Alfresco 4.2c

### ISSUE THREAD

**Issue by Jero8** [share-extras/reset-password-dialog#2]
After putting the .jar (2.0.1) in the shared/lib folder within tomcat's folder and restarting the server, the module does not show up in Share's module deployment page. Hence, the recover password link is not available on the login page of Share.
Tried other modules and they are showing up fine and can be added. Are there any dependencies other then just putting the jar files within the shared folder or is something wrong with this plugin?

Thanks,
Jero

**Comment by davefx** [comment]
I get the same behaviour with Alfresco Community 5.0.c, running on the last Debian 7. I have copied the .jar in /opt/alfresco5.0.c/tomcat/shared/lib, and I have checked that the shared.loader line in catalina properties loads all the .jar files in that directory.

But after restart Alfresco, the module is not shown in share/page/modules/deploy

Any clue about how to find out why the .jar is not been correctly proccessed?

**Comment by davefx** [comment]
OK. My problem is that I was installing the version 2.0.1 JAR from code.google.com. After installing the version 2.1.0 from github (https://github.com/share-extras/reset-password-dialog/releases) everything is working perfectly.

**Comment by wabson** [comment]
Thanks @davefx for testing that. @Jero8 are you able to confirm that the 2.1.0 version fixes your problem?

**Comment by Jero8** [comment]
Thank you, this version fixes my problem!

**Comment by wabson** [comment]
Thanks for confirming. I've removed those downloads from the old project.

Are you able to close this issue please?
