### ISSUE TITLE
Please, migrate to Alfresco 5.0

### ISSUE THREAD

**Issue by davefx** [share-extras/reset-password-dialog#7]
The last supported version is Alfresco 4. Please, add support for Alfresco Community 5.0.

**Comment by wabson** [comment]
Hi, what exactly is the problem on Alfresco 5.0?

**Comment by marioct-zz** [comment]
I´m using with Alfresco 5.0.a  
Additionally i have submited a pull request for portuguese translation https://github.com/share-extras/reset-password-dialog/pull/5

**Comment by davefx** [comment]
Sorry: I supposed version 5.0 wasn't supported, as all the documentation say that the supported versions are 3 & 4.
